backend:
  name: github
  repo: eeedvan/edvanlima-site
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "projects"
    label: "Projetos"
    files:
      - file: "content/projects.json"
        label: "Lista de Projetos"
        name: "projects"
        fields:
          - label: "Projetos"
            name: "projects"
            widget: "list"
            fields:
              - {label: "Slug", name: "slug", widget: "string"}
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Formato", name: "format", widget: "string"}
              - {label: "Capa", name: "cover", widget: "image"}
              - {label: "Descrição", name: "description", widget: "text"}